(defvar *example*
"............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............")

(defun parse (input)
  (loop for line in (sequence-split input '(#\Newline))
        for y from 0
        append (loop for char across line
                     for x from 0
                     when (char/= char #\.)
                     collect (cons char (cons x y)))))

(parse *example*)